import os
import json
import uuid
import re
import math
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Rate limiting
# ---------------------------------------------------------------------------
# 10 submissions per minute (burst protection) and 100 per day (abuse prevention).
# A legitimate writer submits work infrequently; these limits stop automated flooding
# while being invisible to real users.
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ---------------------------------------------------------------------------
# Audit log (structured JSON, one entry per line)
# ---------------------------------------------------------------------------
LOG_FILE = "audit_log.jsonl"


def write_log(entry: dict):
    """Append a structured entry to the audit log."""
    with open(LOG_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")


def read_log() -> list:
    """Return all audit log entries as a list of dicts."""
    if not os.path.exists(LOG_FILE):
        return []
    entries = []
    with open(LOG_FILE, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    entries.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    return entries


def update_log_entry(content_id: str, updates: dict) -> bool:
    """
    Rewrite the log file with updated fields for the matching content_id.
    Returns True if an entry was found and updated, False otherwise.
    """
    entries = read_log()
    found = False
    for entry in entries:
        if entry.get("content_id") == content_id:
            entry.update(updates)
            found = True
            break
    if found:
        with open(LOG_FILE, "w") as f:
            for entry in entries:
                f.write(json.dumps(entry) + "\n")
    return found


# ---------------------------------------------------------------------------
# Signal 1: LLM classification via Groq
# ---------------------------------------------------------------------------

def llm_signal(text: str) -> dict:
    """
    Ask the LLM to assess whether the text reads as human- or AI-generated.
    Returns {"ai_score": float 0–1, "reasoning": str}.
    Higher ai_score = more likely AI-generated.
    """
    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

    prompt = f"""You are an expert at distinguishing human-written text from AI-generated text.

Analyze the following piece of writing and assess the probability that it was generated by an AI.

Return ONLY a JSON object in this exact format, with no preamble, no explanation outside the JSON, and no markdown:
{{"ai_score": <float between 0.0 and 1.0>, "reasoning": "<one sentence explanation>"}}

Where ai_score is:
- Close to 1.0 if you are confident it is AI-generated
- Close to 0.0 if you are confident it is human-written
- Around 0.5 if you are uncertain

TEXT TO ANALYZE:
\"\"\"
{text}
\"\"\"
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        max_tokens=200,
    )

    raw = response.choices[0].message.content.strip()

    # Strip markdown fences if the model wraps the JSON anyway
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)

    try:
        result = json.loads(raw)
        ai_score = float(result.get("ai_score", 0.5))
        ai_score = max(0.0, min(1.0, ai_score))  # clamp to [0, 1]
        reasoning = result.get("reasoning", "")
    except (json.JSONDecodeError, ValueError):
        # Fallback: uncertain if parsing fails
        ai_score = 0.5
        reasoning = "Could not parse model response."

    return {"ai_score": ai_score, "reasoning": reasoning}


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics (pure Python)
# ---------------------------------------------------------------------------

def _sentence_length_variance_score(sentences: list[str]) -> float:
    """
    Low variance in sentence length → AI-like (score near 1).
    High variance → human-like (score near 0).
    Normalized so that variance ≤ 5 maps to ~1.0 and variance ≥ 80 maps to ~0.0.
    """
    if len(sentences) < 2:
        return 0.5  # not enough data

    lengths = [len(s.split()) for s in sentences if s.strip()]
    if len(lengths) < 2:
        return 0.5

    mean = sum(lengths) / len(lengths)
    variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)

    # Map std_dev to AI-likeness: low std_dev → high AI score
    # std_dev of 0–3 → score ~1.0; std_dev of 20+ → score ~0.0
    score = max(0.0, min(1.0, 1.0 - (std_dev / 20.0)))
    return score


def _type_token_ratio_score(words: list[str]) -> float:
    """
    TTR = unique words / total words.
    AI text tends toward moderate TTR (~0.4–0.6).
    Human text is more variable — sometimes very low (repetitive poetry),
    sometimes very high (dense prose).
    We score distance from AI's typical TTR band as human-like.
    A TTR near 0.5 → AI-like (score 1.0).
    TTR far from 0.5 (very low or very high) → human-like (score 0.0).
    """
    if not words:
        return 0.5

    ttr = len(set(w.lower() for w in words)) / len(words)
    # Distance from 0.5 (the AI "center")
    distance = abs(ttr - 0.5)
    # Max distance is 0.5 (TTR of 0 or 1)
    score = max(0.0, min(1.0, 1.0 - (distance / 0.5)))
    return score


def _punctuation_density_score(text: str) -> float:
    """
    AI text tends toward clean, sparse punctuation.
    Human text often has denser/more varied punctuation.
    High punctuation density → human-like (score 0.0).
    Low punctuation density → AI-like (score 1.0).
    """
    if not text:
        return 0.5

    punct_chars = set('.,;:!?—–-…()[]"\'/\\')
    punct_count = sum(1 for c in text if c in punct_chars)
    density = punct_count / len(text)

    # Typical AI density ~0.03–0.06; human ~0.07–0.12+
    # Map: density ≤ 0.03 → score 1.0; density ≥ 0.10 → score 0.0
    score = max(0.0, min(1.0, 1.0 - ((density - 0.03) / 0.07)))
    return score


def stylometric_signal(text: str) -> dict:
    """
    Compute stylometric AI-likeness score from three heuristics.
    Returns {"stylo_score": float 0–1, "metrics": {...}}.
    Higher stylo_score = more AI-like surface properties.
    """
    # Tokenize
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    words = re.findall(r'\b\w+\b', text)

    slv = _sentence_length_variance_score(sentences)
    ttr = _type_token_ratio_score(words)
    pd  = _punctuation_density_score(text)

    stylo_score = (slv + ttr + pd) / 3.0

    return {
        "stylo_score": round(stylo_score, 4),
        "metrics": {
            "sentence_length_variance_score": round(slv, 4),
            "type_token_ratio_score": round(ttr, 4),
            "punctuation_density_score": round(pd, 4),
            "word_count": len(words),
        },
    }


# ---------------------------------------------------------------------------
# Confidence scoring
# ---------------------------------------------------------------------------

def compute_confidence(llm_score: float, stylo_score: float) -> dict:
    """
    Weighted combination: LLM 65%, stylometrics 35%.
    Returns {"confidence": float, "attribution": str}.
    """
    confidence = round((llm_score * 0.65) + (stylo_score * 0.35), 4)

    if confidence <= 0.35:
        attribution = "likely_human"
    elif confidence <= 0.69:
        attribution = "uncertain"
    else:
        attribution = "likely_ai"

    return {"confidence": confidence, "attribution": attribution}


# ---------------------------------------------------------------------------
# Transparency label generation
# ---------------------------------------------------------------------------

def generate_label(attribution: str) -> dict:
    """
    Map attribution result to the transparency label shown to readers.
    Returns {"headline": str, "body": str, "appeal_note": str | None}.
    """
    if attribution == "likely_human":
        return {
            "headline": "Appears to be human-written",
            "body": (
                "Our system found no strong signals of AI-generated content. "
                "This is an automated assessment and not a guarantee of authenticity."
            ),
            "appeal_note": None,
        }
    elif attribution == "uncertain":
        return {
            "headline": "Attribution unclear",
            "body": (
                "Our system was unable to confidently determine whether this content "
                "was human-written or AI-generated. This does not mean the content is inauthentic."
            ),
            "appeal_note": "If you're the creator and believe this is incorrect, you can submit an appeal.",
        }
    else:  # likely_ai
        return {
            "headline": "May contain AI-generated content",
            "body": (
                "Our system found signals consistent with AI-generated writing. "
                "This is an automated assessment and may not be accurate."
            ),
            "appeal_note": "If you're the creator and believe this is incorrect, you can submit an appeal.",
        }


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON."}), 400

    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    # Run signals
    llm_result = llm_signal(text)
    stylo_result = stylometric_signal(text)

    # Score
    scoring = compute_confidence(llm_result["ai_score"], stylo_result["stylo_score"])
    label = generate_label(scoring["attribution"])

    # Audit log entry
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "status": "classified",
        "attribution": scoring["attribution"],
        "confidence": scoring["confidence"],
        "llm_score": llm_result["ai_score"],
        "llm_reasoning": llm_result["reasoning"],
        "stylo_score": stylo_result["stylo_score"],
        "stylo_metrics": stylo_result["metrics"],
        "label_headline": label["headline"],
        "word_count": stylo_result["metrics"]["word_count"],
    }
    write_log(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": scoring["attribution"],
        "confidence": scoring["confidence"],
        "label": label,
        "signals": {
            "llm_score": llm_result["ai_score"],
            "llm_reasoning": llm_result["reasoning"],
            "stylo_score": stylo_result["stylo_score"],
            "stylo_metrics": stylo_result["metrics"],
        },
        "timestamp": timestamp,
    }), 200


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON."}), 400

    content_id = data.get("content_id", "").strip()
    creator_reasoning = data.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "Missing required field: content_id"}), 400
    if not creator_reasoning:
        return jsonify({"error": "Missing required field: creator_reasoning"}), 400

    # Look up original entry
    entries = read_log()
    original = next((e for e in entries if e.get("content_id") == content_id), None)

    if not original:
        return jsonify({"error": f"No submission found with content_id: {content_id}"}), 404

    if original.get("status") == "under_review":
        return jsonify({
            "error": "An appeal has already been filed for this content. Duplicate appeals are not accepted."
        }), 400

    # Update entry
    appeal_timestamp = datetime.now(timezone.utc).isoformat()
    updated = update_log_entry(content_id, {
        "status": "under_review",
        "appeal_reasoning": creator_reasoning,
        "appeal_timestamp": appeal_timestamp,
    })

    if not updated:
        return jsonify({"error": "Failed to update log entry."}), 500

    return jsonify({
        "status": "appeal_received",
        "content_id": content_id,
        "message": (
            "Your appeal has been received and the content is now under review. "
            "A human reviewer will examine your submission and reasoning."
        ),
        "appeal_timestamp": appeal_timestamp,
    }), 200


@app.route("/log", methods=["GET"])
def get_log():
    entries = read_log()
    # Return most recent first
    return jsonify({"entries": list(reversed(entries)), "count": len(entries)}), 200


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    app.run(debug=True)
